### ISSUE TITLE
Themes and CSS styles.

### ISSUE THREAD

**Issue by h-hub** [phillip-kruger/jello#2]
Hi @phillip-kruger ,

Did you use a theme for this Application? or integrated Bootstrap?

I cannot figure out how you designed the UI.

Thanks.

**Comment by phillip-kruger** [comment]
Hi @h-hub I use admin-faces: https://github.com/phillip-kruger/jello/blob/239c05c1c3926bc0dddc8a56d79e586217c7d152/jello-cards/pom.xml#L45

https://adminfaces.github.io/site/

**Comment by h-hub** [comment]
Thanks for the info.
